### ISSUE TITLE
FileNotFoundError: [Errno 2] collect_pile_no_intron.txt

### ISSUE THREAD

**Issue by assetdaniyarov** [sihaohuanguc/Nanopore_psU#5]
```
(base) prom@PC48A067:/data/pipeline/NanoPsiPy/bin$ ./NanoPsiPy_estimation \
-i /data/3jan2024_DirectRNA_second/1/20240103_1055_2F_PAI53967_ccf89b53/fastq_pass/ \
-r /data/PublicData/rna_refseq/gencode.v45.pc_transcripts.fa \
-o /data/3jan2024_DirectRNA_second/1/NanoPsiPy_estimation_1.csv \
-s treatment

[M::mm_idx_gen::5.716*1.67] collected minimizers
[M::mm_idx_gen::7.490*1.99] sorted minimizers
[M::main::7.538*1.98] loaded/built the index for 111048 target sequence(s)
[M::mm_mapopt_update::7.892*1.94] mid_occ = 128
[M::mm_idx_stat] kmer size: 14; skip: 5; is_hpc: 0; #seq: 111048
[M::mm_idx_stat::8.128*1.91] distinct minimizers: 17924026 (28.25% are singletons); average occurrences: 4.998; average spacing: 2.971; total length: 266167009
[M::main] Version: 2.26-r1175
[M::main] CMD: minimap2 -ax splice -uf -k14 --secondary=no /data/PublicData/rna_refseq/gencode.v45.pc_transcripts.fa /data/pipeline/NanoPsiPy/bin/temp/all_pass_fastq.fastq
[M::main] Real time: 8.226 sec; CPU: 15.606 sec; Peak RSS: 2.885 GB
Traceback (most recent call last):
  File "/data/pipeline/NanoPsiPy/bin/./NanoPsiPy_estimation", line 48, in <module>
    ex_fe()
  File "/data/miniconda3_2023/lib/python3.11/site-packages/NanoPsiPy/Pseudo_U_estimation.py", line 105, in ex_fe
    with open(plus_file, "r") as input_file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/pipeline/NanoPsiPy/bin/alignment/plus_strand/collect_pile_no_intron.txt'
(base) prom@PC48A067:/data/pipeline/NanoPsiPy/bin$ 
```

**Comment by assetdaniyarov** [comment]
only .fasta is used as an input, not .fastq.gz
